addons:
  apt:
    sources:
    - libsqlite3-dev
    - sqlite3
language: ruby
rvm:
  - 2.3.1
  - 2.4.3
  - 2.5.0
  - jruby
before_install: gem install bundler -v 1.16.1
before_install: gem install sqlite3 -v 1.3.11
